theme: jekyll-theme-tactile
title: Harnessing geospatial analysis to tackle physical climate risk
description: Examples of maps generated for research purposes using projections from climate models and open source data
